# Generated by Django 6.0.2 on 2026-02-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_content_video_url_alter_siteconfig_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('webseries', 'Web Series'), ('shortfilm', 'Short Film'), ('podcast', 'Podcast')], max_length=20),
        ),
    ]
